name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    # Secrets are located under an environment gh secret list -e DOCKER
    environment: DOCKER # 🔑 use DOCKER environment

    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tags
        id: vars
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      # Log in to Docker Hub (set secrets in repo settings)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sirajudheenam/hello-app

      # Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sirajudheenam/hello-app:latest
            sirajudheenam/hello-app:${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha }}

      # 🔹 Update README with latest tag
      - name: Update README with latest tag using auto commit
        run: |
          TAG="${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha }}"
          sed -i "s|sirajudheenam/hello-app:.*|sirajudheenam/hello-app:${TAG}|" README.md

      # 🔹 Commit README change back to repo
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README with latest docker image tag"
          file_pattern: README.md